# Generated by Django 6.0.3 on 2026-03-27 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewmovie',
            name='movie_rating',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
